services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/ABCD123456abc
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
